### ISSUE TITLE
Fetch and encode IEV term from Electropedia

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/iev#2]
First in English, then in given language

**Comment by opoudjis** [comment]
We need the following method implemented in the IEV gem:

`def get(code, lang)`

Go to the page `http://www.electropedia.org/iev/iev.nsf/display?openform&ievref={code}`, and return the term in language {lang}

So, given http://www.electropedia.org/iev/iev.nsf/display?openform&ievref=103-01-02,

get("103-01-02", "en") should fetch the text "functional". I don't think it also needs to fetch the definition, "function for which the argument is a function and the value a number", let alone the note associated with the definition; but maybe allow for it anyway, in a return structure: :term, :definition, :note...

get("103-01-02", "sr") should fetch the text "функционал, м јд". I see that some of those entries (the Serbian and German) have grammatical information, which eventually will need to be stripped; leave them alone for now.

**Comment by andrew2net** [comment]
@opoudjis ok, I'll finish RFCBib this week and then implement the functionality.

**Comment by andrew2net** [comment]
@opoudjis done
