### ISSUE TITLE
Move iev cache to same directory as relaton cache

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/iev#6]

**Comment by opoudjis** [comment]
@ronaldtse I've just put the relaton caches in ~/.relaton/cache and ./relaton/cache. Is it OK to put the IEV cache in  ~/.relaton/ievcache and ./relaton/ievcache?

**Comment by ronaldtse** [comment]
Are the IEV cache entries different from Relaton cache entries? If they are perhaps they shouldn't be in the same directory?

**Comment by opoudjis** [comment]
They are different, which is why I am proposing to put them in a sibling subdirectory. But I can just put them in a different directory, like ievcache. 

that said, you got me to customise the local case name in document attributes. I think it is better to put both caches under the same directory specified in attributes, than to specify two different directories.

**Comment by opoudjis** [comment]
Since these conceptually do very different things and are independent of each other, no compelling reason to do this.
